#!/usr/bin/env bash
#
# ~/.xinitrc
#

[[ -f /etc/X11/xinit/.Xresources ]] && xrdb -merge /etc/X11/xinit/.Xresources
[[ -f "$HOME/.Xresources" ]] && xrdb -merge "$HOME/.Xresources"

[[ -f /etc/X11/xinit/.Xmodmap ]] && xmodmap /etc/X11/xinit/.Xmodmap
[[ -f "$HOME/.Xmodmap" ]] && xmodmap "$HOME/.Xmodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# fixed slow startup of gtk applications
# https://wiki.archlinux.org/title/XDG_Desktop_Portal
# https://unix.stackexchange.com/questions/748596/very-slow-launch-for-some-applications-after-update-to-debian-12/748604#748604
export XDG_CURRENT_DESKTOP=""
export WLR_NO_HARDWARE_CURSORS=1
export WLR_RENDERER="gles2"
export LIBSEAT_BACKEND="logind"
systemctl --user import-environment DISPLAY DBUS_SESSION_BUS_ADDRESS XDG_CURRENT_DESKTOP WLR_NO_HARDWARE_CURSORS WLR_RENDERER LIBSEAT_BACKEND
dbus-update-activation-environment --systemd DISPLAY DBUS_SESSION_BUS_ADDRESS XDG_CURRENT_DESKTOP WLR_NO_HARDWARE_CURSORS WLR_RENDERER LIBSEAT_BACKEND
