#!/usr/bin/ash

run_earlyhook() {
    if [ -n "${ip}" ] && [ -n "${pxe_nfs_srv}" ]; then
        # Module autoloading
        modprobe nfs 2>/dev/null
    fi
}

run_hook() {
    if [ -n "${ip}" ] && [ -n "${pxe_nfs_srv}" ]; then
        pxe_nfs_srv=$(eval echo "${pxe_nfs_srv}")

        # enable chained nfs mount handler
        export mount_handler="pxe_nfs_mount_handler"
    fi
}

pxe_nfs_mount_handler() {
    newroot="${1}"
    
    msg ":: Boot PXE over NFS"

    # mount the nfs directly as boot mount
    msg ":: Mount NFS share '${pxe_nfs_srv}'"
    local mount_status
    if [ -n "${pxe_nfs_opt}" ]; then
        mkdir -p "${boot_mnt}"
        nfsmount -o "${pxe_nfs_opt}" "${pxe_nfs_srv}" "${boot_mnt}"
        mount_status=$?
    else
        mkdir -p "${boot_mnt}"
        nfsmount "${pxe_nfs_srv}" "${boot_mnt}"
        mount_status=$?
    fi
    if [ "$mount_status" -gt 0 ]; then
        echo "!! ERROR: failed to mount '${pxe_nfs_srv}'"
        launch_interactive_shell
    fi

    pxe_mount_handler "${newroot}"
}
