#!/usr/bin/ash

run_earlyhook() {
    if [ -n "${ip}" ] && [ -n "${pxe_nvmeof_srv}" ]; then
        # Module autoloading
        modprobe nvme_tcp 2>/dev/null
    fi
}

run_hook() {
    if [ -n "${ip}" ] && [ -n "${pxe_nvmeof_srv}" ]; then
        pxe_nvmeof_srv=$(eval echo "${pxe_nvmeof_srv}")

        # enable chained nvmeof mount handler
        export mount_handler="pxe_nvmeof_mount_handler"
    fi
}

pxe_nvmeof_mount_handler() {
    newroot="${1}"
    
    msg ":: Boot PXE over NVMeoF"
    tee /etc/nvme/hostnqn <<EOF
nqn.2014-08.org.nvmexpress:uuid:$( uuidgen )
EOF
    tee /etc/nvme/hostid <<EOF
$( uuidgen )
EOF
    tee /etc/nvme/discovery.conf <<EOF
--transport=tcp --traddr=${pxe_nvmeof_srv} --trsvcid=8009
EOF

    # 1st: connect the nvmeof filesystem
    msg ":: Connect NVMeoF to '${pxe_nvmeof_srv}'"
    nvme connect-all
    
    # 2nd: check the copy to RAM filesystem is present
    if ! mountpoint -q "${copytoram_mnt}"; then
        msg ":: Mount ${copytoram_mnt} (tmpfs) filesystem, size=${copytoram_size}"
        mount --mkdir -t tmpfs -o "size=${copytoram_size}",mode=0755 copytoram "${copytoram_mnt}"
    fi

    # 3rd: place the nvmeof filesystem as softlink inside the RAM filesystem
    msg ":: Wait for NVMeoF device"
    matched=""
    while [ -z "${matched}" ]; do
        for i in /dev/nvme*; do
            if [ "${i//n1}" != "${i}" ]; then
                matched="${i}"
                break
            fi
        done
        sleep 2
    done
    mkdir -p "${copytoram_mnt}/arch/x86_64"
    msg ":: Link ${matched} into the RAM filesystem"
    ln -s "${matched}" "${copytoram_mnt}/arch/x86_64/pxeboot.img"

    # 4th: mount the RAM filesystem as boot mount
    msg ":: Bindmount '${copytoram_mnt}' as '${boot_mnt}'"
    if ! mount --mkdir -o bind "${copytoram_mnt}" "${boot_mnt}"; then
        echo "!! ERROR: failed to mount '${copytoram_mnt}'"
        launch_interactive_shell
    fi

    pxe_mount_handler "${newroot}"

    # last: when the image is copied to RAM, the NVMeoF needs to be
    #       closed as the boot process will hang (#bug)
    if [ "${copytoram}" = "y" ]; then
        msg ":: Disconnect NVMeoF from '${pxe_nvmeof_srv}'"
        nvme disconnect-all
    fi
}
